### ISSUE TITLE
Assigned submission disappeared from my JOSS dashboard

### ISSUE THREAD

**Issue by jgostick** [openjournals/joss#1019]
I was editing a submission (https://github.com/openjournals/joss-reviews/issues/3426) and it disappeared from my dashboard midway through the process.  I _think_ this occurred because I set myself as a reviewer since the 2nd reviewer disappeared.  I am not sure if this is the expected behaivor or not, but I had a hard time doing my editorial duties when I was unable to see it in my dashboard, so I think it is probably not ideal.

**Comment by xuanxu** [comment]
This is not the expected behavior, as long as you are the editor you should see it in your dashboard. I've been searching through the code and could not find the source for this bug. 
Did the paper disappear from your dashboard before it was withdrawn? The dashboard only lists "in progress" submissions.

**Comment by jgostick** [comment]
Yes it was before the withdraw.  If the 'in progress' tag is removed, will it disappear from the dashboard?  Maybe this tag was removed by accident?  It tagged it "withdrawn" the other day and the "in progress" tag was not there.

**Comment by arfon** [comment]
Hrm. Not sure what happened here but I've not been able to find an underlying issue here so will close for now. Feel free to re-open if this happens again.
