### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by WheeSci** [openjournals/joss#1043]
Hi,
I just put a bunch of stuff on my github page and I think it may be appropriate for joss.  The material is all part of a single project intended to allow non-experts to design, fabricate and build low cost, high quality spectrometers.  The issue is that the project is spread across a number of repositories.  There is a design repository, a firmware repository, a repository of STL files and a repository for the user interface.  I broke it up like this because that will make it easier for users to download only what they need.  Will this be a problem for reviewers?  Should I take any steps to make sure it is all considered as part of a single paper?
I am attaching the markdown doc that I just wrote so you can see what I have there.
Thanks for your consideration,
Jack
(summers@wcu.edu)
[paper.md](https://github.com/openjournals/joss/files/8082972/paper.md)

**Comment by arfon** [comment]
Hi @WheeSci. These definitely look like interesting projects but don't look to be quite right for JOSS. For example, many of them aren't software, the focus of the project looks to be open hardware (not really in scope for us), and also looks to have an education rather than research focus. 

Perhaps I've missed something? Did you take a look at our submission requirements/scope section of our docs by any chance? https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software
