### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by lucaskup** [openjournals/joss#1044]
Hello, I and my colleagues at [Vizlab](http://vizlab.unisinos.br/) have been using in the last two years an application I have developed. It allows us to open, visualize and process hyperspectral data collected using spectroradiometers. This software was used in some scientific publications such as [Kerogen Type Classification in Hydrocarbon Source Rocks Using Hyperspectral Data and Machine Learning](https://ieeexplore.ieee.org/document/9554771).

The repo is found [here](https://github.com/lucaskup/SpectralData) and it is possible to use a live demo [here](https://spectral-data.herokuapp.com/)

Does it qualify as a submission to JOSS?

**Comment by arfon** [comment]
Possibly, although packages that focus on visualisation are generally out of scope for JOSS.

Looking at the repo, it's a little challenging to figure out where the main contributions from you (the authors) are, as opposed to dependencies such as `d3.js`. Could you link directly to the main application logic that has been created as part of this work?

**Comment by lucaskup** [comment]
I would say that the main application logic is in [sample.js](https://github.com/lucaskup/SpectralData/blob/master/public/source/sample.js) and [smoth_derivative.js](https://github.com/lucaskup/SpectralData/blob/master/public/source/smoth_derivative.js) source files, although there is some app logic in [view_controller.js](https://github.com/lucaskup/SpectralData/blob/master/public/source/view_controller.js) as well. The [chart.js](https://github.com/lucaskup/SpectralData/blob/master/public/source/chart.js) is mainly for handling alterations in the SVG graph by calling appropriate functions of `d3.js` as the user interacts with the plot.

**Comment by arfon** [comment]
Apologies for the slow reply. This looks like it would be out of scope for us sorry. Mostly because it looks like it would fall foul of our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.
