### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by mercicle** [openjournals/joss#1101]
Hi Editorial Board, 

Was hoping to get a pre-submission assessment for our paper. This is based on my M.S. work and my capstone -unpublished- paper was called "EntropiQ: A Cloud Platform for Entanglement Analytics of Many-body Quantum Mechanical System Simulations." We're going to modify this paper ([which you can find for a limited time here](https://drive.google.com/file/d/1a7h3Zda6wphKoDBZA1MyDk_g4A184HGP/view?usp=sharing) - just skip to section 3) and write a submission to JOSS for EntropiQ itself. 

Problem: coding, running, managing and analytics of larger-scale many-body quantum mechanical system simulations requires software, computational, and cloud expertise most theoretical physicists do not have
Solution: EntropiQ has three parts: 1. Underlying postgres database (deployment of which can be replicated in AWS) for the management and governance of simulations (both metadata and simulation results); 2. set of simulation pipelines that can act as templates for creating new experimental designs; 3. A Streamlit (Python) Application designed also as a starter-kit and template for end-to-end management and analysis of experiments (simulation). So EntropiQ is not a library, but a platform that can be used by a community and/or suite of starter-kits that can be customized internally within a lab. 

Perhaps the most important reason to submit to JOSS -rather than use Entropiq to present results solely in a physics journal (we plan to do this too)-  is we hope to attract other contributors to add to the core functionality of the community app version to enable low/no-code capabilities to design and run experimental designs (rather than having many labs fork and customize in their own cloud). 

Best,
John

**Comment by danielskatz** [comment]
Can you tell us where the open source software is?

**Comment by mercicle** [comment]
Hi @danielskatz, made it available here: https://github.com/mercicle/entropiq thanks!

**Comment by danielskatz** [comment]
Thanks @mercicle 

I'm not sure I have an immediate answer. I'll be curious to see what other @openjournals/joss-editors think.

**Comment by mercicle** [comment]
Hi @danielskatz can you ping the editors again as a little reminder after the holiday? thx!

**Comment by jbytecode** [comment]
Hi @mercicle, I took a look at the software repository and may I ask a couple of questions?

- It seems the repo includes several code from different languages including Julia and Python.
- There are some Julia files (e.g. `julia_install_packages.jl`) which are responsible to download and install the requirements. Standard Julia packages have a well-defined package structure with a Project.toml file that defines the pre-requisites. In its current form, the repo does not hold a software package but a couple of files.
- What is the main language? It seems some of Python files (e.g. create_clifford_group) read some `h5` file content and are they perform utility stuff. If the main language is Julia, those Python codes can be loaded and ran in Julia through `PyCall` package. I think one can easly find a Julia version of those `h5` readers. [HDF5](https://juliaio.github.io/HDF5.jl/stable/).
- Since my area of expertise is not physics, I can't make any judgments about the content. It would be good to consult other editors' opinions on this and other issues.

**Comment by arfon** [comment]
Thanks @jbytecode! I agree with you that this repository doesn't really appear to be software designed for _maintainable extension_ (see our submission requirement language below), but rather looks to be a collection of scripts.

From https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements:

> In addition, JOSS requires that software should be feature-complete (i.e., no half-baked solutions), packaged appropriately according to common community standards for the programming language being used (e.g., [Python](https://packaging.python.org/), [R](https://r-pkgs.org/index.html)), and designed for **maintainable extension** (not one-off modifications of existing tools). “Minor utility” packages, including “thin” API clients, and single-function packages are not acceptable.

@mercicle – based on my inspection, I would say this isn't suitable for JOSS as it appears to be a collection of scripts to accomplish a task rather than a software package.
