### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by ftherrien** [openjournals/joss#1115]
Hi,

I have created a package named [VaspGibbs](https://github.com/ftherrien/VaspGibbs) to simplify the process of getting Gibbs free energy from [VASP](https://www.vasp.at/) calculations. The physics of VaspGibbs are not new and other large packages ([vaspkit](https://vaspkit.com/index.html) and [ASE](https://wiki.fysik.dtu.dk/ase/)) have functions that can accomplish these tasks, but VaspGibbs makes the process easy and does not require the users (1) to know python (2) have an in-depth understanding of the thermodynamics involved. Other widely used DFT codes like Gaussian can return Gibbs free energy directly. VaspGibbs aims to provide that functionality for VASP users.

My concerns are:
 1. VaspGibbs is open source and has no dependencies other than numpy, but VASP is not. How does that fitt with JOSS's rules?
 2. VaspGibbs is useful, but it does not contain new physics.

Would it be suitable for JOSS? If not what kind of improvements/features would make it suitable?

Thanks,

Félix

**Comment by rkurchin** [comment]
Hey Félix! Neither of your two listed concerns would be disqualifying from JOSS's perspective. Given the relatively modest size of the codebase, I suspect the concern you might run into with submission would be the [Substantial Scholarly Effort](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort) criterion. Maybe take a read through that and see what you think. If you believe it meets the criterion, go ahead and submit! But I'll warn you now, it will likely trigger a scope query due to the smallish LOC, so you'll have to explain the scholarly effort side at that point.

You mentioned in your email to me that collaborators were looking for a way to cite the code – obviously JOSS can be a great solution for that, but if it turns out VaspGibbs isn't a fit for JOSS, it is very easy to just generate a DOI for a software release using e.g. figshare or Zenodo.

**Comment by ftherrien** [comment]
Thanks Rachel!
