### ISSUE TITLE
Need volume and issue numbers

### ISSUE THREAD

**Issue by labarba** [openjournals/joss#124]
In the interest of citations looking more like "normal" journal papers—and given the role of this journal to fill that need for software citations—it would be a good idea to assign volume and issue numbers. It could be as simple as a rule of one volume per calendar year (so we are in Volume 1 now), and one issue per month (or per 25 papers, or any arbitrary number that sounds reasonable). 

Papers should have some id number also, so a citation would look like: 
Vol. 1 (Issue 1): 01234, doi

**Comment by arfon** [comment]
👍 yeah that's a good idea @labarba. I've been wondering what to do about that. I think 1 volume per year and 1 issue per month sounds good (assuming we keep up this pace of submissions).

**Comment by danielskatz** [comment]
this was also something I brought up in #107 but that part may have gotten lost in the middle of the thread.

**Comment by Kevin-Mattheus-Moerman** [comment]
I would not loose sleep if you decide to implement this but I think I disagree that the volume and issue numbers are required. Given all the new purely online and open publication systems (some of which have also abandoned the name "journal") that are popping up, I suspect the volume/issue format will soon become really old fashioned. Not having the volume/issue reference should become the norm pretty soon. Reference managers are also already able to cope with this, so I am not sure if there is any real problem to not having these. I feel that as a new online journal we should promote the change.

**Comment by labarba** [comment]
@Kevin-Mattheus-Moerman Well, maybe not the number, but the volume is a required field in BibTeX 
See:
https://en.wikipedia.org/wiki/BibTeX#Entry_types

`article`
An article from a journal or magazine.
Required fields: author, title, journal, year, volume

**Comment by kyleniemeyer** [comment]
I agree that a modern, purely online journal doesn't really *need* volume or issue numbers, but one of the stated objectives of JOSS is to hack the existing system—so our articles should contain the basic attributes of a journal article. I think many traditional journals have mostly eliminated issue numbers anyways (at least, I don't see them as frequently) but I don't think having a per-year volume number is too onerous. We could probably even use the year itself as a volume number, but starting this year with 1 is pretty easy.

Actually, since this is a software journal, I propose we start the volume numbering at 0.

... although Fortran/Matlab folks might not understand 😄

**Comment by genomematt** [comment]
What about Ubuntu style 16(05):13

**Comment by danielskatz** [comment]
I would also like to have an article identifier as part of the journal, which could simply be the github issue number for the submission.  We could say this was the issue number, and just have one volume, or this could be the page number.  JORS uses page numbers that are eN, where N is the article number within the current volume, and the volumes seem to increase by one each year.

**Comment by arfon** [comment]
> I would also like to have an article identifier as part of the journal, which could simply be the github issue number for the submission. We could say this was the issue number, and just have one volume, or this could be the page number. JORS uses page numbers that are eN, where N is the article number within the current volume, and the volumes seem to increase by one each year.

👍 this sounds good to me @danielskatz. I currently use the GitHub review issue id to construct the JOSS DOIs e.g. for http://dx.doi.org/10.21105/joss.00017 the review issue is [`#17`](https://github.com/openjournals/joss-reviews/issues/17). So based on @danielskatz's suggestion the format I propose that we publish 1 volume per year so http://dx.doi.org/10.21105/joss.00017 would be:

JOSS, Vol. 1 (Issue 23), http://dx.doi.org/10.21105/joss.00017

**Comment by kyleniemeyer** [comment]
Sounds great! Although I'm going to again propose starting at volume 0 👍

**Comment by arfon** [comment]
> Sounds great! Although I'm going to again propose starting at volume 0 👍

Lol, I'm genuinely concerned that we'll break some combination of Medeley/Crossref/Google Scholar if we do this.

**Comment by danielskatz** [comment]
I wonder about having issue numbers that are not a consecutive sequence. (Yes, I know I suggested this earlier.)

**Comment by arfon** [comment]
> I wonder about having issue numbers that are not a consecutive sequence. (Yes, I know I suggested this earlier.)

Hrm, good point. We'd also be publishing papers with issue numbers out of order, i.e. depending on how long the review takes http://dx.doi.org/10.21105/joss.00017 could be published months after http://dx.doi.org/10.21105/joss.00018

That said, does any of this _actually_ matter (as long as we have volume/issue numbers). It's not like we're printing copies to be placed in order on a library shelf...

**Comment by danielskatz** [comment]
I have no idea - The real question is who does know if this matters?

**Comment by arfon** [comment]
¯\_(ツ)_/¯

**Comment by jackiekazil** [comment]
(WARNING - I am not a librarian, but I worked on processing Marc records with @dchud.) 

One of the things I dealt with was the bib records. Here is the big secret -- no records are neat or neatly organized. It is big mess. Be consistent. 

*[This is how volume, issues, edition information is officially classified.](https://www.loc.gov/marc/bibliographic/bd362.html)*

So, there are formatted and unformatted possibilities. If you decide to go unformatted, then it will be stored as free text. If you go as formatted, then there is the ability to sort when searching. For the purpose of sorting, I would say some sort of order on the edition should be used. 

I think you could just do.... 
```
0#$a1
0#$a2
....
0#$a746
```
Since the fields can vary so much, I expect that Google or whomever would be able to handle it without the 'vol' & 'no.'. 

That being said, the "main" provider in the library field for records is OCLC. Forgive me, I am not sure how far along this project is, but the metadata for articles (aka Marc records) should be written to the **[Worldcat API](https://www.oclc.org/developer/develop/web-services/worldcat-metadata-api.en.html)** for classification in other data stores. It is my guess this this where Google gets its data from. 

/me waves @dchud
/me waves @labarba -- we chatted at PyCon after your keynote. Great talk!

**Comment by jackiekazil** [comment]
/me celebrates library knowledge not being completely lost.

**Comment by arfon** [comment]
In the end I went with the following:

- One volume per year. 2016 is volume (1)
- One issue per month since launch in May 2016. We're currently on issue (3).

Crossref metadata is updated with this information. I'll be updating the JOSS site shortly which will include links to `doi2bib` e.g. http://www.doi2bib.org/#/doi/10.21105/joss.00011
