### ISSUE TITLE
Editor profile link sometimes broken

### ISSUE THREAD

**Issue by flokno** [openjournals/joss#1309]
The link to the editor's webpage (or github profile) is not fully functional in at least two of the recently published JOSS papers:

Examples:
When opening https://joss.theoj.org/papers/10.21105/joss.05810 in Firefox, clicking on `Antonia Mey` links to https://www.theoj.org/joss-papers/joss.05810/Mey-research.org for which I get a 404 error.

Same behavior in https://joss.theoj.org/papers/10.21105/joss.06150 for `Rachel Kurchin` which links to https://www.theoj.org/joss-papers/joss.06150/rkurchin.github.io , same error.

It works in https://joss.theoj.org/papers/10.21105/joss.06154 which takes me to https://marcel.stimberg.info/ as probably intended.

I get the same errors when downloading the file and using macOS Preview.

I do not get the error when using Adobe Acrobat Reader instead.

**Comment by xuanxu** [comment]
The URL for an editor comes from the information they fill in their own editor profile. In the cases you mention it looks like they have entered their URL without the `http://` part so the browser takes them as relative (`https://www.theoj.org/joss-papers/joss.05810/Mey-research.org` instead of just `Mey-research.org`). 

Updating the URL in the editor profile page to include the protocol part (http or https) should fix the problem. 
(cc/ @ppxasjsm @rkurchin)
BTW same thing happens with the links in the public profiles at https://joss.theoj.org/about#editorial_board

I'll look into adding some validation in the editors profile form.
