### ISSUE TITLE
GitHub badges for review (and papers edited) counts

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#1385]
Currently it's possible to create a GitHub badge for a README with the DOI for a paper. What if we made it possible for a reviewer to link easily to their reviews on JOSS? We already have a URL that links to the reviews for a reviewer (e.g., https://joss.theoj.org/papers/reviewed_by/@speth) and the same for editors (https://joss.theoj.org/papers/edited_by/@arfon)

**Comment by sneakers-the-rat** [comment]
I have a free hour to procrastinate before getting back into writing mode and this seems doable. I'm surprised we don't have a `Reviewer` model in the repo. that would be sort of the natural way to do it so it would mirror the `Paper#status` method, but since i get the sense that we don't want to touch this repository that much, I can just make a `badges` controller and do it that way. 

The `reviewed_by` route is currently going to the `papers#filter` controller, and it seems wrong to tack the badge on beneath that in the controller.
