### ISSUE TITLE
Pre-submission Inquiry: Example of major version updates

### ISSUE THREAD

**Issue by jackiekazil** [openjournals/joss#1403]
Hello -- I am from [Project Mesa](https://github.com/projectmesa). We are drafting a JOSS article to discuss the significant updates from the first two publications (2015 & 2020) to now. 

**Q1: Can you point me to examples of papers that were significant version updates, not introduction papers?** 
I found a previous issue discussion (e.g., https://github.com/openjournals/joss/issues/1162), but I wonder if you have any specific examples of papers that were significant version updates, not original papers?  I am hoping example papers might help us figure out how to handle nuanced but impactful updates where the change is essential, but the foundational information we are including may feel _known_ (or previously published). When does repeating things conceptually and omitting them in other places make sense or not? As software becomes more complex, this becomes more difficult without ignoring word count limits.

**Comment by EwoutH** [comment]
Hi JOSS team, I'm Ewout, another Mesa maintainer and working with Jackie on our paper. I'd like to provide some additional context that may help clarify the situation and ongoing discussions within the Mesa team.

We've been having extensive internal discussions about how to structure our next MESA paper, with two main approaches being considered:

1. An "update paper" focused primarily on changes since our last publication (2020)
2. A "current state" paper that presents MESA 3.x as a complete, standalone work

Through our discussions, a few considerations have emerged:

- Our previous papers were published in 2015 and 2020, making this a roughly 5-year cycle
- MESA has undergone significant architectural changes with version 3.0
- The primary audience appears to be academic users who may be encountering MESA for the first time through this paper
- We aim to make the paper independently readable without requiring reference to previous publications

Some guidance or examples of how other projects have handled similar situations would be appreciated. We're particularly interested in understanding how to balance providing necessary context while maintaining focus on current functionality within JOSS's scope and length constraints.

**Comment by EwoutH** [comment]
We've aligned on this internally and are happy with the current state. Our pre-review submission is now tracked in https://github.com/openjournals/joss-reviews/issues/7620.

For future reference some insights from the editors on this topic would still be appreciated!

**Comment by danielskatz** [comment]
I know that we've had multiple versions of papers/software before, but I don't remember specifics. I'll see if other editors do.

**Comment by danielskatz** [comment]
Regarding the question about what goes in a paper on a new version, I think the paper needs to stand alone, at a high level, but it could reference a prior paper for details.

**Comment by EwoutH** [comment]
We went in that direction so that's great to hear!

**Comment by jackiekazil** [comment]
Thank you for the response! I am going to consider this resolved for now -- but if others have an opinion, please feel free to add it.
