### ISSUE TITLE
OSI Affiliate membership

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [openjournals/joss#155]
Hi all, 

We need to decide on OSI affiliate membership. I wrote up the below together with the OSI. Read through and feel free to post questions. 

I believe affiliate membership of the OSI is a great way to get support from the OSI and become formally associate with and recognized by the OSI. The OSI can also play a role in fiscal sponsorship (an issue that was recently raised https://github.com/openjournals/joss/issues/154). 

Look forward to hear your thoughts. 

Kevin

---

The OSI ([Open Source Initiative](https://opensource.org/)) is the founding organization of the open source software movement, internationally recognized as the steward of the [Open Source Definition](https://opensource.org/docs/osd), and best known for certifying and maintaining the [list of open source
licenses](https://opensource.org/licenses/alphabetical).

The OSI has expressed a lot of interest in JOSS and are keen to collaborate with us closely. They have several current and past Board Directors who are university faculty and researchers. They have
suggested we become [affiliate members](https://opensource.org/affiliates/about) of the OSI.

There are no costs associated with affiliate membership. The affiliate member program allows organizations—unequivocally independent groups with a clear commitment to open source—to join the OSI in support of their mission, "to educate about and advocate for the benefits of open source, and to build bridges among different constituencies in the open source community." As an affiliate member JOSS will not lose any of our independence, yet we will gain access to a variety of support and services, e.g. infrastructure, promotion, networking and fiscal sponsorship.

Through membership, JOSS acknowledges the authority of the OSD and the OSI's role in certifying licenses, and in turn the OSI would promote and recognize JOSS as the canonical journal for open source research software. If desired, as mentioned above, the OSI can serve as a [fiscal sponsor](https://www.councilofnonprofits.org/tools-resources/fiscal-sponsorship-nonprofits), collecting (tax-free) donations on our behalf.

There are several qualifications for affiliate membership, see the "User Communities" section of the [affiliate criteria page](https://opensource.org/AffiliateRequirements). JOSS would need to ensure that, as a journal, we act in line with the OSI's standards specific to open source licensing. We do this to a large extend by mentioning and linking to the Open Source Definition on our website, and by requiring an OSI approved open source license for our submissions.

In addition JOSS would name a representative to serve as a liaison between the two organizations. Most significantly, the representatives votes on behalf of JOSS in OSI Board of Director elections, and can nominate candidates for open Board Director seats. Also an OSI representative will be invited to join the JOSS board to support that we do indeed adhere to the OSI definitions.

**Comment by labarba** [comment]
It sounds like becoming an OSI affiliate member is well-aligned with our mission and needs.

A minor note on aspiring to be _"the canonical journal for open source software"_ — remember that  JOSS is focused on software as a product of research or for research use. This means we can't cover the plethora of open-source software and their goals.

**Comment by Kevin-Mattheus-Moerman** [comment]
Yes that sounded confusing. I updated the text with "open source research software".

**Comment by danielskatz** [comment]
This seems fine to me.  (Nit: loose -> lose)

**Comment by tracykteal** [comment]
Thanks @Kevin-Mattheus-Moerman I'm +1 on OSI affiliation. I'd be interested in learning more about their fiscal sponsorship terms though. Do they have documentation for that?

**Comment by Kevin-Mattheus-Moerman** [comment]
@tracykteal great. I'll request more details on those terms. I believe the OSI takes a certain percentage of the donated funds and that we would need to report once a year on how the money was spend. I'll post more details on this here shortly.

**Comment by profmasson** [comment]
Thought I'd save Kevin some time and effort as go between and just answer directly...

As a U.S. based non-profit (501-c3) OSI can serve as a fiscal sponsor offering our "legal and tax-exempt status to groups engaged in activities related to the organization's missions. It typically involves a fee-based contractual arrangement between a project and an established non-profit." - [Wikipedia](http://en.wikipedia.org/wiki/Fiscal_sponsorship)

In order to set this up, we need a project proposal from JOSS, describing what the funding will be for and how it aligns with OSI's mission, "to educate about and advocate for the benefits of open source and to build bridges among different constituencies in the open source community."

You can see examples with, [Snowdrift.coop](https://wiki.opensource.org/bin/Main/Open+Source+Initiative+Working+Groups/Snowdrift.coop+sponsorship+proposal/) and [OpenHatch](https://wiki.opensource.org/bin/Main/Projects/Fiscal+Sponsorships/OpenHatch/).

Once that is in the Board would need to approve the sponsorship.

Once approved, implementation is pretty straight forward, donations can be sent into OSI (made payable to OSI), but are marked for JOSS. The OSI charges a small overhead for administrative costs--we do not make a profit on our sponsorships--and passes the remainder of those donations along to JOSS. This is currently 5%.

Those we sponsor set up a donations page that names OSI as the fiscal sponsor for the program and sends contributors to OSI's PayPal account. We can also take checks sent to our address in Palo Alto.

OSI can recognize those donations in PayPal (i.e., distinguish them from donations meant for OSI), and our bookkeeper, then breaks out these donations in her monthly reports to the OSI.

JOSS would then invoice OSI for disbursements as needed, providing enough description each time to satisfy us that the funded activities were in line with the approved project (as mentioned above) and indeed within OSI's mission as well as within the scope of JOSS' project (not that there's any practical doubt about either; it's just to make sure we're all square in case the IRS ever wants documentation).

There is some ongoing management & administration required. In addition to the requests for disbursement, we need an a signed grant agreement
([BLANKFiscalSponsorshipGrantAgreement.pdf](https://github.com/openjournals/joss/files/379811/BLANKFiscalSponsorshipGrantAgreement.pdf)) and an annual report
([OSIFiscalSponsorReportForm.pdf](https://github.com/openjournals/joss/files/379812/OSIFiscalSponsorReportForm.pdf)) that explains how the funding was used.

Hope that makes sense? You can view this on our [wiki](https://wiki.opensource.org/bin/Main/Projects/Fiscal+Sponsorships/), although it's not explained as clearly--as wiki's tend to be... :-)

Let me know if you have any other questions - thanks!

**Comment by arfon** [comment]
This looks great @Kevin-Mattheus-Moerman - I think this is something we should do. 

@profmasson - thanks for the background on the fiscal sponsorship stuff. We've been discussing that a little over in https://github.com/openjournals/joss/issues/154 but I think it makes sense for the OSI to handle this for us if you can.

@Kevin-Mattheus-Moerman @profmasson - what are the next steps on formalizing this relationship?

**Comment by cMadan** [comment]
I completely agree, I think having a formal relationship with OSI would be great.

It would also be great if OSI can be help with the finances (mediating donations). It's awesome that @arfon has been covering expenses thus far, but it would be good to move to a more sustainable plan.

**Comment by labarba** [comment]
@arfon Next steps are (1) writing and submitting a project proposal to OSI; (2) waiting for OSI Board to meet and approve FSA; (3) signing FSA agreement with OSI.

**Comment by kyleniemeyer** [comment]
This sounds like a great idea for JOSS 👍

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer @labarba @arfon submitted all the forms and signed all agreements in relation to affiliate membership. The OSI board has also approved these. So hurrah on that! I'll post an official announcement on this shortly together with @profmasson. We still need to set-up fiscal sponsorship though (we decided to move that to 2017 to avoid tax difficulties) and I'll keep you up to date on those developments.

**Comment by arfon** [comment]
:shipit: https://twitter.com/OpenSourceOrg/status/846710254377353216
