### ISSUE TITLE
Can GitHub support JOSS publications with pro bono LFS support for supporting repos?

### ISSUE THREAD

**Issue by davclark** [openjournals/joss#160]
TSSIA, but to give a concrete use-case:

Currently we are scratching our heads over the best place to put annoyingly-but-not-too-big data that supports the tests / examples for a functional brain imaging pre-processing step. If you're curious, the code is [here](https://github.com/KKI-CNIR/aCompCor) (though pretty much uninterpretable as yet to the uninitiated).

It would obviously be easiest to just sitck the data in git LFS. But, we are academic researchers and know that committing to pay $5/mo. on soft money is not a good bet. So, we're more likely to put it in the JHU library Dataverse or something, which makes things more complicated for everyone.

I know JOSS is somewhat independent of GitHub (the company), but given @arfon's involvement, this seems like a fairly straightforward ask to get a quick yes/no/maybe.

**Comment by kyleniemeyer** [comment]
You might be interested in checking out the recently accepted JOSS paper on PyGBe (https://dx.doi.org/10.21105/joss.00043), which grabs some large mesh files necessary for tests from Zenodo rather than including them in the directory.

This might be a solution for you to avoid storing the large files in the repository itself—I imagine you could use Figshare similarly.

**Comment by davclark** [comment]
No doubt. Figshare, dataverse (probably at Hopkins, but maybe Harvard), and neurovault are all options for us.

It's just added complexity.

**Comment by arfon** [comment]
> I know JOSS is somewhat independent of GitHub (the company), but given @arfon's involvement, this seems like a fairly straightforward ask to get a quick yes/no/maybe.

We've not done this for any other open source projects as far as I know so I'm pretty sure this is a 'no'.

Sorry for dragging you in to a random discussion @jonathansick but I seem to remember you exploring the idea of setting up a third-party Git-LFS server for LSST. Did that ever get shipped?

**Comment by jonathansick** [comment]
Yep, at LSST we're running our own Git LFS storage server. It's set up so that anyone can anonymously clone data repos, but only people in the lsst GitHub org can push.

There's a technical note talking about the implementation at https://sqr-001.lsst.io (admittedly it may not be the clearest doc. It does have links to the open source repos that run it. I can refer you to our LFS engineering lead if you need clarification).

Our user docs are at https://developer.lsst.io/tools/git_lfs.html Setting up auth for our users is a little awkward because we go slightly against the grain of GitHub's implementation.

Other than that, it's free-as-in-S3 LFS for our community, which is pretty great.

**Comment by arfon** [comment]
Awesome, thanks @jonathansick. I'd love to see someone like Zenodo offer a Git-LFS interface at some point for community use 🤔

**Comment by davclark** [comment]
Thanks for the pointer @jonathansick. I'm going to call my question answered. As  per usual, I'm not surprised physics already has a solution here, and the complexity of that solution is almost certainly a no-go for most neuroscience researchers at this point. I'm unlikely to get the resources for such a solution where I am at Kennedy Krieger!
