### ISSUE TITLE
Some Crossref metadata inconsistent with uploaded metadata

### ISSUE THREAD

**Issue by kyleniemeyer** [openjournals/joss#162]
I was playing with the Crossref API and noticed that the metadata for JOSS papers (or at least the most recent one) that Crossref returns is somewhat inconsistent with what is submitted.

For example, for the PyGBE paper (https://dx.doi.org/10.21105/joss.00043), Crossref returns the following metadata (available https://api.crossref.org/v1/works/http://dx.doi.org/10.21105/joss.00043):

```
{
    "status": "ok",
    "message-type": "work",
    "message-version": "1.0.0",
    "message": {
        "indexed": {
            "date-parts": [
                [2016, 8, 18]
            ],
            "date-time": "2016-08-18T17:42:27Z",
            "timestamp": 1471542147109
        },
        "reference-count": 10,
        "publisher": "The Open Journal",
        "issue": "4",
        "published-print": {
            "date-parts": [
                [2016, 8, 18]
            ]
        },
        "DOI": "10.21105\/joss.00043",
        "type": "journal-article",
        "created": {
            "date-parts": [
                [2016, 8, 18]
            ],
            "date-time": "2016-08-18T16:08:57Z",
            "timestamp": 1471536537000
        },
        "source": "CrossRef",
        "title": ["PyGBe: Python, GPUs and Boundary elements for biomolecular electrostatics"],
        "prefix": "http:\/\/id.crossref.org\/prefix\/10.21105",
        "volume": "1",
        "author": [{
            "affiliation": [],
            "family": "D. Cooper",
            "given": "Christopher",
            "ORCID": "http:\/\/orcid.org\/0000-0003-0282-8998"
        }, {
            "affiliation": [],
            "family": "C. Clementi",
            "given": "Natalia",
            "ORCID": "http:\/\/orcid.org\/0000-0002-0575-5520"
        }, {
            "affiliation": [],
            "family": "Forsyth",
            "given": "Gilbert",
            "ORCID": "http:\/\/orcid.org\/0000-0002-4983-1978"
        }, {
            "affiliation": [],
            "family": "A. Barba",
            "given": "Lorena",
            "ORCID": "http:\/\/orcid.org\/0000-0001-5812-2711"
        }],
        "member": "http:\/\/id.crossref.org\/member\/8722",
        "container-title": ["JOSS", "The Journal of Open Source Software"],
        "deposited": {
            "date-parts": [
                [2016, 8, 18]
            ],
            "date-time": "2016-08-18T16:08:58Z",
            "timestamp": 1471536538000
        },
        "score": 1.0,
        "subtitle": [],
        "issued": {
            "date-parts": [
                [2016, 8, 18]
            ]
        },
        "URL": "http:\/\/dx.doi.org\/10.21105\/joss.00043"
    }
}
```

The things that stand out to me most are `"reference-count": 10`, when the paper only has four references, and `published-print`, when the paper is only published online.

If you look at the submitted XML (https://github.com/openjournals/joss-papers/blob/master/joss.00043/10.21105.joss.00043.crossref.xml), there is no information about the reference count submitted—so I have no idea where that's coming from—and the publication is clearly given as online only (rather than **print**) with `<publication_date media_type="online">`.

**Comment by augustfly** [comment]
There are 10 `<citation>` elements in the `<citation_list>` of the submitted XML -- the four DOIs shown in the HTML/PDF reference list, which have been stripped of text, a fifth DOI from somewhere else, and 5 more unstructured references from somewhere else. 

After a little digging the crossref references appear to match the entries in the `paper.bib` file in the original repo: https://github.com/barbagroup/pygbe/blob/master/paper.bib -- if a DOI existed in that bibtex file then it added straight away otherwise it appears the bibtex was converted to a unstructured text blob --goodness there must be a probabilistic title=>DOI resolver out there for the other 5, all of which have DOIs minted long before the software was JOSSed. 

I can't speculate as to why the JOSS HTML/PDF refs and the CrossRef/paper.bib refs so wildly disagree. Having submitted metadata >= article metadata is a rather unusual stance. More often than not it's the other way round.  

FWIW at least three of les six extra references are "_Papers published using PyGBe_" type references based on their listing as such in the original repo `README.` I'll have to take time to have a think about what that actually means semantically... Of course, you actually suggested that they do this, @kyleniemeyer, when you reviewed it!
