### ISSUE TITLE
How do I responsibly adjust my notification settings?

### ISSUE THREAD

**Issue by ctb** [openjournals/joss#173]
I'm getting dozens of e-mails b/c I'm on the joss-reviewers team and I'm seeing all the whedon commands. I don't want to turn off all notifications, but right now I'm getting too much e-mail. What should I do?

thx!

**Comment by arfon** [comment]
@ctb sorry about this. I've just deleted the JOSS-reviewers team (we can re-instate it later if we decide) as this is essentially deprecated because of the progress we've made on addressing the feedback in this issue https://github.com/openjournals/joss/issues/125 

Also, please make sure you're not watching the https://github.com/openjournals/joss-reviews repository.

<img width="984" alt="notifications" src="https://cloud.githubusercontent.com/assets/4483/18714047/5f32a826-7fc9-11e6-83f5-75e3ea4db56b.png">

For future reviews we plan to have editors reach out directly to potential reviewers

**Comment by ctb** [comment]
I'm still getting the e-mails -- e.g. I got https://github.com/openjournals/joss-reviews/issues/55#issuecomment-248648255. I've unsubscribed etc.  Seems like maybe github caches the joss-reviewers team?

**Comment by arfon** [comment]
Hrm, does it show you as subscribed in the right-hand column under 'notifications'?

I suspect you may have to manually unsubscribe from all of these threads 😿 

The good news is, this won't happen any longer (on newer threads)...

**Comment by ctb** [comment]
I am not a fan :).
