### ISSUE TITLE
Is it ok to use YAML references field?

### ISSUE THREAD

**Issue by hadley** [openjournals/joss#181]
Instead of a separate metadata field (as described in http://pandoc.org/MANUAL.html#citations).

Since all of these files need to live in the root directory, it would be nice to minimise the footprint of a JOSS citation.

**Comment by arfon** [comment]
Would this be instead of bibtex? If so, I'm afraid we don't support this currently. The submission and paper-compilation process is heavily automated and the current editorial tools require the references to be in a bibtex file: https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L156-L164

I'm not sure if I've completely understood your question here so please followup if I've missed the point.

**Comment by hadley** [comment]
I suspect it's a one line change to that command, or it may possibly already work.

**Comment by hadley** [comment]
The more I think about this, the more I think it will already work:

> As an alternative to specifying a bibliography file using --bibliography or the YAML metadata field bibliography, you can include the citation data directly in the references field of the document’s YAML metadata. The field should contain an array of YAML-encoded references, for example:

...

**Comment by arfon** [comment]
> The more I think about this, the more I think it will already work:

🆒 Feel free to point me at a working example and I'll see if I can compile it.
