### ISSUE TITLE
What is "the software archive"?

### ISSUE THREAD

**Issue by hadley** [openjournals/joss#182]
I don't understand this requirement: "A list of key references including a link to the software archive". What is the software archive? For an R package, is it CRAN? It seems weird to be forced to cite something in the paper that I'm creating so that people can cite the software.

**Comment by arfon** [comment]
👋 @hadley. Sorry for not making this clearer. We require all authors to archive a copy of their software with a service like figshare or Zenodo. For example https://github.com/openjournals/joss-reviews/issues/79 has an archive of their repository over at http://doi.org/10.5281/zenodo.158941

CRAN or any other package manager doesn't meet the requirements here as it's not designed to be a long-term archiving solution.

**Comment by hadley** [comment]
If the point of JOSS is to provide something to cite, why wouldn't people just cite the zenodo archive?

What criteria does a long-term archive have to meet? I'd think CRAN would be a strong position because (a) it's already been around for a long time (~15 years), (b) apples LOCKSS principle, and (c) is under the aegis of a non-profit foundation.

**Comment by arfon** [comment]
> If the point of JOSS is to provide something to cite, why wouldn't people just cite the zenodo archive?

Because Zenodo archives/DOIs and citations to them don't count in the same way as a paper with a CrossRef DOI. The goal is for JOSS to be indexed by Google Scholar, Scopus, Web of Science etc and for these papers (and their associated citations) to result in career credit for the author. BTW, I wrote a bunch about this in this announcement blog post: http://www.arfon.org/announcing-the-journal-of-open-source-software

> What criteria does a long-term archive have to meet? I'd think CRAN would be a strong position because (a) it's already been around for a long time (~15 years), (b) apples LOCKSS principle, and (c) is under the aegis of a non-profit foundation.

Primarily it needs to have archiving in its mission. Services such as Zenodo have long-term archiving in their mission (see _Preservation of data_ in https://zenodo.org/policies). While package managers are often very stable I don't believe preservation is their main function.
