### ISSUE TITLE
Papers should contain literature review and statement of contribution

### ISSUE THREAD

**Issue by joseph-hellerstein** [openjournals/joss#194]
I think this is a wonderful effort, especially to provide metrics that establish the importance of software contributions to provide a foundation for software contributions to be included in academic evaluations.

One thing that seems to be missing from the paper submission is a section that includes a literature review and statement of contribution. This information is typically contained in a 1 to 2 page introduction section of an academic paper. These statements document: (a) the importance of the problem addressed; (b) the shortcomings of existing solutions; and (c) how the software addresses these shortcomings. Step (b) includes citations, the key metrics for academics to evaluate impact. This is foundational to make software contributions count for academic hiring and promotions.

Writing an additional 1-2 pages seems to be a modest increase in the work that's already required for a submission. In particular, considerable effort is required for writing documentation, unit tests, installation procedures as well as usage examples. So, I don't think that you're asking a lot more from submitters.

A next step after this is to take into account the quality of the contribution in the review process. These are _software_ contributions. So, it should be about addressing a gap in tools or services. Or, a new way of solving existing problems that is more elegant.

Once again, this is a great effort.

**Comment by labarba** [comment]
According to the [Reviewer Guidelines](http://joss.theoj.org/about#reviewer_guidelines), a "Statement of need" _is_ required.

>**A statement of need**
>The authors should clearly state what problems the software is designed to solve and who the target audience is.

However, it is requested that it be included in the code Documentation, rather than in the "paper" (although a summary can be included there, too). 

References should be included in the paper. However, I disagree that this should amount to a *literature review.* In fact, I don't even agree that a regular paper should include a (lengthy) literature review in the Introduction section. The Introduction of a regular paper should give some background, sure, but only of the works that one builds upon. The purpose is to identify what is the gap in knowledge that the work is meant to fill, followed by a statement of how the authors will go about it. See, for example, the relevant lesson of the Stanford **"Writing in the Sciences"** course:
https://youtu.be/Hmi0T1NCX2w

**Comment by arfon** [comment]
Thanks for the feedback @joseph-hellerstein, it's much appreciated.

> Writing an additional 1-2 pages seems to be a modest increase in the work that's already required for a submission. In particular, considerable effort is required for writing documentation, unit tests, installation procedures as well as usage examples. So, I don't think that you're asking a lot more from submitters.

Unfortunately most of these ideas take us a long way from our goal of having _very_ short summary paper for JOSS submissions.

It's possible that in the future we'll accept longer-form full papers but for now we're pretty happy with what we have already.
