### ISSUE TITLE
Feed for papers

### ISSUE THREAD

**Issue by noamross** [openjournals/joss#202]
I'd like a feed for JOSS papers (all, included pending/submitted, though I guess it would make sense to have multiple feeds so that people can pick if they only want to see accepted papers).

**Comment by arfon** [comment]
Thanks for posting this @noamross. Turns out I _did_ implement this although it's somewhat hidden:

`http://joss.theoj.org/papers/popular.atom` 👈  accepted papers (you can paginate through this with  e.g. `http://joss.theoj.org/papers/popular.atom?page=2`
`http://joss.theoj.org/papers.atom` 👈  all papers (same pagination params)

**Comment by noamross** [comment]
Great, thanks!
