### ISSUE TITLE
How are reviewers assigned?

### ISSUE THREAD

**Issue by jayjaybillings** [openjournals/joss#207]
How are reviewers assigned? Similar to #200 I have received a lot of emails, but unlike with other journals I have never received a specific request to review a paper.

**Comment by arfon** [comment]
Hi @jayjaybillings. Reviewer assignment happens in threads like this: https://github.com/openjournals/joss-reviews/issues/132

It looks like you're not listed in the `reviewers.csv` file here: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv - would you mind adding yourself to this file so that we know we can call on you in the future?

**Comment by jayjaybillings** [comment]
@arfon Thanks!
