### ISSUE TITLE
Contact info missing in code of conduct

### ISSUE THREAD

**Issue by CoralineAda** [openjournals/joss#239]
There's a spot near the bottom where you need to insert an email address or other contact mechanism for reporting CoC violations.

**Comment by kyleniemeyer** [comment]
@CoralineAda thanks for catching this!

@arfon The text is currently `Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]`; do we want to specify you (and otherwise point to the editorial board list), a publicly accessible address for the entire editorial board, or a subset of people who volunteer to be the CoC "subcommittee"?

My preference would probably be the first or last options.

**Comment by CoralineAda** [comment]
Not me, I’m not responsible for your CoC violations ;)

It should be one or more publicly accessible email addresses for whoever is responsible.

Thanks!
Coraline

**Comment by arfon** [comment]
Thanks for spotting this @CoralineAda.

I've added my email for now in https://github.com/openjournals/joss/pull/240, ultimately this should probably be a dedicated email for journal administrators.
