### ISSUE TITLE
Education software eligible for JOSS?

### ISSUE THREAD

**Issue by funsim** [openjournals/joss#247]
Would you consider software to improve (university-level) education eligible for submission to JOSS?

Our case is a Python software that allows to create and manage "virtual classrooms" on github.

**Comment by labarba** [comment]
JOSS has (so far) made a statement that it will publish _research_ software. This excludes software developed for educational purposes. (Someone should start another journal for that!)

**Comment by funsim** [comment]
@labarba: Yes, currently the guidelines state that the software must be directly related to research. However, since education and research are tightly linked, my question is if JOSS is willing to _extend_ their scope to also allow for educational software?

**Comment by arfon** [comment]
> @labarba: Yes, currently the guidelines state that the software must be directly related to research. However, since education and research are tightly linked, my question is if JOSS is willing to extend its scope to also allow for educational software?

Hi @funsim - thanks for posting this. As @labarba pointed out, this kind of software would currently be considered out of scope. I'm reluctant to increase the scope of JOSS beyond its current function but I'm sympathetic to this idea.

I'd love to hear more from @openjournals/joss-editors about this.

**Comment by katyhuff** [comment]
Is there any aspect of _education research_ in this software? (e.g. does it skill metrics to assess learning outcomes). I, too, am sympathetic to the idea.

**Comment by kyleniemeyer** [comment]
I hesitate to say that I'm also sympathetic because it's starting to sound repetitive :yum: but I am, in part because JOSS is likely the only venue that could publish such software.

I agree with @katyhuff that an argument for the software being used for educational research would help, but otherwise if this is something that is well designed, reusable, documented, tested, etc., then perhaps it should be considered.

**Comment by Kevin-Mattheus-Moerman** [comment]
I agree with @katyhuff + @kyleniemeyer. I think we can consider educational software if it is also research software or, I'd like to add, if it is useful in a future research setting. I suppose part of the point of JOSS is to give academics credit for their academically relevant software. I.e. other researchers/academics will start using and citing the work. To publish in JOSS it must be important to the authors that the work is first peer reviewed and that the accepted version is made citable. JOSS citations are "worth more" than than a simple GitHub->Zenodo DOI style citation. So, is it wrong to say that author submitting work to JOSS always expect their work to be used in a research setting where others will start citing the work? Otherwise there is no point in submitting to JOSS. 
If the submitted educational software has a clear research application or it seems likely the work will be featured / cited in future research projects then it seems reasonable to me to consider such submissions.

**Comment by labarba** [comment]
As most of you know, I'm very active in (open) education in computational science, and my group does produce educational materials and code. Despite this, I think educational software needs another journal dedicated to that, and it would be spreading JOSS too thin to expand the scope for including it.

**Comment by tracykteal** [comment]
I am also sympathetic to educational software and think it's very important, and my guess is that another journal like JOSS dedicated to educational software is unlikely to emerge in the short term. However, keeping this journal scoped to research software is an important constraint.

@funsin, as @katyhuff suggests, is there a educational research component to this software? Is it tracking any metrics that could allow people to use it to assess educational outcomes, effectiveness of a teaching strategy or engagement with course content?

**Comment by funsim** [comment]
Thank you for the active and fruitful discussions!

After discussing this with the core-developer, Aslak Bergersen, we currently do not see an educational research component - instead the software is really a tool to facilitates digital classroom education. Also, our primary motivation for publishing the software is to achieve a wider adaptation, not citations. As such, it seems that a publication to JOSS might not be ideal format, and instead a blog post might be more suitable.

**Comment by tracykteal** [comment]
Thanks for the good question, and please let us know when the blog post goes up. It sounds like many people in this community would be interested in the software you've developed!

**Comment by Kevin-Mattheus-Moerman** [comment]
@funsim If you still want to make it citable (but not through JOSS with a paper etc) you can simply use Zenodo as explained here: https://guides.github.com/activities/citable-code/

**Comment by funsim** [comment]
Thanks!
