### ISSUE TITLE
Question on the WTFPL license 

### ISSUE THREAD

**Issue by leofang** [openjournals/joss#248]
Hello,

I couldn't find any way to contact the editorial board on the JOSS website, so I suppose this place is the best one to ask questions about the journal?

I'm interested in publishing our code in JOSS, but I noticed one issue: our code is planned to be released under the [WTFPL](http://www.wtfpl.net), which is recognized by FSF but not OSI. Is it possible for us to stick to the WTFPL, or at least adding a statement in the end of our paper like "This work is released under either the WTFPL or the MIT license. Users are allowed to choose either license, but such decision should be made and followed when using, forking, or modifying this work." 

Thank you.

**Comment by danielskatz** [comment]
JOSS requires an OSI-approved license.

**Comment by massonpj** [comment]
If you are going to dual license the project, "This work is released under either the WTFPL or the MIT license," then wouldn't that satisfy the requirement?

**Comment by pjotrp** [comment]
I think we should expand and allow FSF approved licenses too. In my opinion the FSF is one of the main authorities: Richard Stallman having started the GNU project AND invented the GPL. They are one of the great champions of FOSS.

**Comment by arfon** [comment]
> I think we should expand and allow FSF approved licenses too.

I'll defer to @massonpj on this. My understanding was that as an OSI affiliate one of our jobs is to support the role of the OSI as the standard-bearer for open source licenses.

**Comment by massonpj** [comment]
My snarky answer is, "It's the Journal of Open Source Software, not the Journal of Free Software." But that pretty much makes me a jerk :-)

My serious response would be to highlight that the FSF does not 'approve' licenses (like the OSI does, https://opensource.org/approval), rather they identify GPL-compatible licenses (https://www.gnu.org/licenses/license-list.en.html). Their approach here is to identify popular licenses, and assess their compatibility with the GPL, as a service to the community.

Interestingly, while the WTFPL, Version 2 is listed as compatible with the GPL, the FSF states, "We do not recommend this license. If you want a lax permissive license for a small program, we recommend the X11 license. A larger program usually ought to be copyleft; but if you are set on using a lax permissive license for one, we recommend the Apache 2.0 license since it protects users from patent treachery."

Finally, I am quite confident that the FSF would not champion FOSS (Free and Open Source Software). RMS has been quite clear on his opinion of open source software, and even the term FOSS (https://www.gnu.org/philosophy/floss-and-foss).

**Comment by leofang** [comment]
So is a dual-license like WTFPL + MIT allowed in JOSS?

I have done my homework before deciding using WTFPL, as to me it's the least thing I am concerned with, and so I want a maximally permissive license, which in my opinion is nothing but the WTFPL. While MIT is good, it's no fun.

Personally, I think that WTFPL is not OSI-approved is probably because they don't like a vulgar name, not because of different political view points (FLOSS vs FOSS, blahblahblah). In fact, when OSI rejected it [(see the minute)](https://opensource.org/minutes20090304), they did not make this decision based on the legal loopholes in the WTFPL that some people criticize, or on the public domain issue as Wikipedia mistakenly cited, but because WTFPL is "as redundant to the Fair License," the latter of which is [OSI-approved](https://opensource.org/licenses/Fair). However, essentially WTFPL and Fair are the same thing, and in this sense allowing WTFPL is still complying OSI standards. :P

**Comment by arfon** [comment]
> So is a dual-license like WTFPL + MIT allowed in JOSS?

Yes I think a dual-license would be acceptable here.
