### ISSUE TITLE
browser says website is insecure

### ISSUE THREAD

**Issue by mvhulten** [openjournals/joss#328]
When I am on the UiB.no network and go to https://joss.theoj.org/, with any web browser, I get a website-is-not-secure warning.  Firefox says this:

```
joss.theoj.org uses an invalid security certificate.
The certificate is only valid for the following names: *.herokuapp.com, herokuapp.com
Error code: SSL_ERROR_BAD_CERT_DOMAIN 
```

Was the certificate intentionally registered for `herokuapp.com`?  Is it safe to add an exception?
This might not be an actual bug of joss, not lastly because it may be an interaction with the ISP('s transparant proxy?), but of the websites I visited so far, I get it only with this one.

**Comment by arfon** [comment]
> Was the certificate intentionally registered for herokuapp.com? Is it safe to add an exception?
This might not be an actual bug of joss, not lastly because it may be an interaction with the ISP('s transparant proxy?), but of the websites I visited so far, I get it only with this one.

This is because the website isn't running on SSL (i.e. use http://joss.theoj.org rather than https://joss.theoj.org).
