### ISSUE TITLE
We should explain what the purpose of paper.json is

### ISSUE THREAD

**Issue by arfon** [openjournals/joss#35]
Ultimately I'd like us to be able to build the full publication (and CrossRef metadata) based on the `paper.json` entry. For now though, it's a somewhat experimental feature but we'd still like authors to include one if possible.

**Comment by hadley** [comment]
Is there a reason the metadata can't simply live in `paper.json`?

**Comment by arfon** [comment]
> Is there a reason the metadata can't simply live in paper.json?
@hadley probably not. I was trying to make this compatible with some related work in https://github.com/CodeMeta/codemeta. You can probably skip this metadata generation step for now.

**Comment by pjotrp** [comment]
Wow, JSON-LD for source code/package meta data - that is a great initiative. I can use that.

**Comment by cboettig** [comment]
Hey @arfon , was just reading your paper on [JOSS, year-in-review](https://twitter.com/arfon/status/884330873407107073) and noticed your discussion of the manual work in generating the crossref metadata.  Definitely seems like something that would be easier to automate if/once authors include a `paper.json` / `codemeta.json` file!  I think on the DataCite side @mfenner already has this conversion automatically, and @krzysztof says that implementing codemeta support on the Zenodo end is in the plans for Q4 of 2017.  So would make sense here as well, and should be easy to map into crossref.  Let me know if there's anything I can do to help.

**Comment by danielskatz** [comment]
I like this idea and think we should try to move in this direction, but I also want to be sure that we don't ignore that fact that the code itself could be in other places besides zenodo, such as figshare.

**Comment by cboettig** [comment]
> code itself could be in other places besides zenodo

@danielskatz yup, definitely.  I'm still in touch with Mark Hanhel as well, codemeta is on their list but they're focused on other things at the moment so we won't see any changes to their metadata model for a while.  (A bit of a shame since that means software archived there will continue to report to datacite that the license is cc-by or cc0).  On a shorter term, we should see support for codemeta in DataONE network in the near future as well; @gothub would have the latest on that. 

Just to be clear, it sounds like the JOSS process involves creating two independent DOIs: a CrossRef DOI assigned by JOSS (ostensibly to the "paper"), and a DataCite DOI created by the data archive, right?  I suppose the assumption is that authors should be citing both the JOSS-generated DOI and the repository-generated DOI then, (e.g. analogous to Dryad's recommendation of citing both data and paper)?  I see the logic, but this feels somewhat redundant all the same.  

In any event, it would be easy to generate CrossRef style metadata from either paper.json or codemeta.json description, they are both (primarily) schema.org now so the relevant fields would look almost identical (though paper.json would use the top-level `@type` of `ScholarlyArticle` instead of `SoftwareSouceCode`

**Comment by arfon** [comment]
👋 @cboettig. Yes, this is definitely interesting and something we should think about doing. When first setting up JOSS I had the idea that the `paper.json` file could essentially be used to automate most of the submission process (see the script to generate it here: https://gist.github.com/arfon/478b2ed49e11f984d6fb). Since then you've all done a bunch of work on CodeMeta and so it's definitely time to revisit this I think.

> Let me know if there's anything I can do to help.

❤️ thanks. Honestly it's just finding some time to work on this. We've recently secured a small amount of funding for JOSS so we should be able to work on this soon.

> Just to be clear, it sounds like the JOSS process involves creating two independent DOIs: a CrossRef DOI assigned by JOSS (ostensibly to the "paper"), and a DataCite DOI created by the data archive, right? I suppose the assumption is that authors should be citing both the JOSS-generated DOI and the repository-generated DOI then, (e.g. analogous to Dryad's recommendation of citing both data and paper)? I see the logic, but this feels somewhat redundant all the same.

There is some redundancy here but I'm not sure how to resolve it. The DataCite/Zenodo/figshare DOI is for the software archive. I think it's very important that there is a software archive associated with each JOSS paper but I agree it's weird that we end up with two DOIs...

**Comment by danielskatz** [comment]
As we wrote in the software citation paper:

> While we strive to offer practical guidelines that acknowledge the current incentive system of academic citation, a more modern system of assigning credit is sorely needed. It is not that academic software needs a separate credit system from that of academic papers, but that the need for credit for research software underscores the need to overhaul the system of credit for all research products.

Ending up with 2 DOIs is another sign of this need for a better system...
