### ISSUE TITLE
JOSS pre-submission enquiry

### ISSUE THREAD

**Issue by mkhorton** [openjournals/joss#354]
Hello,

I have a query regarding your policy towards sub-packages/plug-ins/sub-modules/etc. -- that is, a new code that is feature complete and does something useful in its own right, but that does depend on an existing larger 'parent' code.

Typically, when people write code like this, they either:

* put their new code in its own standalone repository, with a list of dependancies that include the parent code

* or, contribute their new code back to the original project as a new sub-module or similar

From an end-user point of view, the latter option is much preferred -- it makes installing and using these codes much easier, and helps with discoverability. We want to encourage people to contribute code back to existing projects. However, many people will do the former simply because it allows them to cite their research/write a paper/etc.

Since the purpose of JOSS is to make it easier for researchers to cite their research code, do you intend to address situations like this?

**Comment by kyleniemeyer** [comment]
Hi @mkhorton—to me the answer is really "it depends."

There are many standalone packages that rely heavily on some other code/library, that would never be incorporated back to the original project. For example, nearly all Python-based scientific codes probably rely on NumPy or SciPy in some way, but I think it's fair to say that most of those will never be a part of either package. In that case, the software would/could be submitted to JOSS as long as it is feature-complete for solving *some* problem etc.

In that case, I don't necessarily agree with 
> We want to encourage people to contribute code back to existing projects.

because that may or may not be appropriate or desired.

On the other hand, if you have some code/package that extends an existing project and it would make sense for it to be a part of that project, then I would say that it makes sense to contribute it and then submit the whole thing to JOSS. If the original package was already published in JOSS, then (assuming the delta is "big" enough) the new version could be published as a second paper, with a different/extended author list. 

We've had at least one case already where we've published two versions of a software package, where v2 has a substantially different feature set. So that is a perfectly suitable option where a small package gets incorporated in a larger project.

**Comment by pjotrp** [comment]
Actually I would argue it is better to have an independent module. Dependency resolution is a solved problem. Separate modules encourage independency, isolation and maintainability.

Even so, there may be good reasons to have it as part of a larger software. You should be able to publish your contribution in that case. Make sure to acknowledge stuff you incorporate from the main project, it may be helpful to invite others as co-authors. In short, give credit where credit is due.

**Comment by mkhorton** [comment]
> Dependency resolution is a solved problem. Separate modules encourage independency, isolation and maintainability.

Agreed that dependency resolution isn't the main issue. I'd argue that separate modules discourage maintainability though: I've seen cases where people write a module, then they leave their postdoc/graduate/etc. and there's no one left to maintain it and it can be left collecting dust. If it's incorporated into a larger project, that project's maintainers will be able to look after it, especially if the larger project introduces breaking changes at some point in its development. Likewise, it helps with documentation and community support.

So that's really where I was coming from when I suggested that "We want to encourage people to contribute code back to existing projects."

That said, from what these comments, it sounds like JOSS is pretty flexible in this regard, which is good to know.

**Comment by danielskatz** [comment]
It seems like this issue can now be closed, so I am doing so.  If anyone feels there's an action here that hasn't been captured, please reopen it and explain what you think needs to be done before it is closed again.
