### ISSUE TITLE
Is it possible to update a published paper?

### ISSUE THREAD

**Issue by Datseris** [openjournals/joss#423]
Hello,

I have published this paper on JOSS: http://joss.theoj.org/papers/10.21105/joss.00458

We have worked on a new version that adds a lot of new features. We are very near into publishing this new version 2.0. 

I have updated the `paper.md` to match the new version, specifically updated the Features List and the Contributors sections. My question is, can the _published_ paper be updated as well, once we do our formal release?

**Comment by labarba** [comment]
No. You cannot change the published paper.

But if the new version has extensive new work, you can submit a new paper.

**Comment by danielskatz** [comment]
It sounds to me like this could be a new paper.

**Comment by Datseris** [comment]
:(

I don't think it is enough to publish a new paper, not do I think it makes much sense; the current one has been cited once, and I'd like to use the same.

I am very surprised by an answer so definitive. Since the journal is all about software papers, and significant software updates happen very often in the huge amount of repositories published here, shouldn't something like this be supported or at least considered?

**Comment by kyleniemeyer** [comment]
We are fairly flexible on the new paper for a new major software version, this has already been done a few times. However, since JOSS is trying to fit within the traditional journal ecosystem, we can't really have papers changing over time.

Plus, a JOSS article is not necessarily the best route for people to cite the most recent version of a software package—we are trying to solve a credit & career issue rather than reproducibility. For the latter, people should be directly citing the specific software version they used in a paper, perhaps in addition to a JOSS article.

So, the typical process (or at least what I would recommend) for software evolution and JOSS would be:
1. Submit the software & paper to JOSS for your software. Once published, add citation information to your README/docs
2. As you make bugfixes and minor version updates, archive these using Zenodo (e.g.) and recommend people cite the DOI for the version they use in addition to the JOSS paper.
3. Once your software progresses to a new major version with substantial changes/new functionality/etc., then you submit a new or updated paper and the software back to JOSS.
4. Repeat steps 2-4 as the software continues to evolve

(This may "dilute" the citations to the individual papers, if people only cite the newest one, so if that is a concern then you may prefer to just do steps 1 and 2.)

**Comment by Datseris** [comment]
Thank you @kyleniemeyer . Okay then, I will simply use the automatically generated zenodo, but will still point people to cite the published article and maybe mention the version the use.
