### ISSUE TITLE
Github username change

### ISSUE THREAD

**Issue by akashnag** [openjournals/joss#676]
If an author updates their username on GitHub as well as JOSS's profile page, while one of their papers is under review, or after their paper has been published, how can they change their repository address in the submitted/published paper?

**Comment by arfon** [comment]
Is this just the username you're asking about or the repository address for the software too?

To answer your question - some updates are possible post-publication for JOSS although within reason. Is there a paper you need updating?

**Comment by Akash-Nag** [comment]
Both, because if I update the username, the repository address (which is bound to the username URL) will also change. Yes, I have a paper currently under review and I was exploring the possibility of changing my username, which therefore will require the repository address for the paper to be updated as well. If you could consider this scenario repeating in future for other authors as well, I think it would be great if JOSS could provide a mechanism for this kind of thing. Otherwise, any changes to the username will lead to linking to an non-existing repository at best, or to a completely wrong repository or profile (if the old username on GitHub is claimed by some other person) at worst.

**Comment by arfon** [comment]
Fixed in the review thread.
