### ISSUE TITLE
Pre-submission enquiry - Citation Style Language

### ISSUE THREAD

**Issue by rmzelle** [openjournals/joss#682]
I'd like to inquire whether the Citation Style Language (CSL, https://citationstyles.org/, https://github.com/citation-style-language/) would be considered in scope for JOSS.

While more of an ecosystem than a single piece of software, CSL forms the backbone of many research-oriented citation tools (such as Zotero, Mendeley, and many others, including your Whedon: https://github.com/openjournals/whedon/pull/31/files). The CSL project offers an XML specification to describe citation formats, maintains a repository with close to 10,000 citation styles, as well as several CSL-oriented software tools (such as a CSL style formatter, validator, and editor). The CSL project does itself not develop any CSL processors (the software libraries that interpret CSL styles and reference metadata to generate rendered citations).

We use multiple licenses, primarily the MIT license for the schema, documentation, and software, and CC-BY-SA for CSL styles and locale files.

**Comment by danielskatz** [comment]
My thought is no, that it is a useful tool but not one that helps researchers **do** research, but others in JOSS might have other opinions

**Comment by rmzelle** [comment]
Isn't authoring manuscripts a big part of daily research life, though? My main drive to work on the CSL project is to help researchers spend less time managing their citations and more time doing actual science. CSL-based software like Zotero also market specifically to researchers ("Your personal research assistant. Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research."; "Mendeley brings your research to life, so you can make an impact on tomorrow").

But I agree it's a bit of a gray area. From our perspective, we haven't found a journal that's a better fit for CSL. Plus it's rather ironic that an open source project for citations isn't easy to cite itself, and people currently are inconsistently citing our XML specification or website, which isn't optimal (such as https://doi.org/10.7717/peerj-cs.214, https://arxiv.org/abs/1703.09109, https://link.springer.com/chapter/10.1007/978-3-319-00026-8_8#Fn2, and http://www.tug.org/TUGboat/tb35-3/tb111stender.pdf).

**Comment by jedbrown** [comment]
The JOSS software stack uses CSL, though JOSS papers don't normally cite CSL. My first inclination was in-line with Dan's, that this is getting too meta. But you've also demonstrated that there is a body of research that cites CSL in a scholarly manner (versus politely citing tooling that does not directly support the research contribution), and when reading through paper titles at the latest ACM/IEEE Joint Conference on Digital Libraries (https://2019.jcdl.org/program/papers/), one can see lots of opportunities to cite packages such as CSL.

I don't find the following compelling as reason for JOSS to accept:
> Isn't authoring manuscripts a big part of daily research life, though? My main drive to work on the CSL project is to help researchers spend less time managing their citations and more time doing actual science.

This is a noble goal and we thank you, but one can say the same about Git or Emacs or libc or using cron to dim the lights and redshift your screen to avoid after-midnight eye distress from impacting your productivity. I don't think it would be appropriate for JOSS to review such submissions _because_ researchers use them to improve their manuscript-authoring lives. Rather, I think JOSS should review CSL because there exists a nontrivial research domain that builds on CSL as part of its scholarship.

**Comment by rmzelle** [comment]
> one can say the same about Git or Emacs or libc or using cron to dim the lights and redshift

These tools have much more general use than CSL, though, which is specifically developed for, and primarily used within, the domain of scholarly publishing. A better comparison would be something like MathML (https://en.wikipedia.org/wiki/MathML, https://scholar.google.com/scholar?hl=en&q=MathML).

**Comment by danielskatz** [comment]
I'm going to close this as no longer active
