### ISSUE TITLE
Pre-submission enquiry - eph

### ISSUE THREAD

**Issue by DiegoKoz** [openjournals/joss#731]
Dear Editorial committee from JOSS,

We would like to publish an article in JOSS related to the package [EPH](https://github.com/holatam/eph), an R package made for handling the Argentinean Permanent Household Survey. This is the main source of information for working on living conditions in Argentinean population and the basic data source for social scientists. Our package is a toolkit for this specific data. As the main audience of the package is from Latin America, the documentation of the package is in Spanish (we consider that this is a way to help close the gap for the many non-english speakers R-users in Argentina). 

We would like to know if It is possible to submit the paper (which of course would be written in English) and try to find a reviewer that is a Spanish-speaker?

Kind Regards,

Diego Kozlowski

**Comment by arfon** [comment]
Hi @DiegoKoz - apologies for the very slow reply here. This looks like a useful piece of software but may be considered out of scope due to:

- The small nature of the software (see https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
- The fact that it's a package very tightly-coupled to this particular dataset (i.e. software might be hard to extend/re-use by others).

It would be useful to see the paper you're proposing - could you compile it at http://whedon.theoj.org and post the PDF here?

> We would like to know if It is possible to submit the paper (which of course would be written in English) and try to find a reviewer that is a Spanish-speaker?

We've never done this before but I think it should be possible.

**Comment by arfon** [comment]
Closing as stale.
