### ISSUE TITLE
Pre-submission inquiry on updated HexWatershed model repository

### ISSUE THREAD

**Issue by changliao1025** [openjournals/joss#825]
Hi, 
I have recently updated our HexWatershed repository to meet the criteria of JOSS.
https://github.com/pnnl/hexwatershed
HexWatershed model is a watershed delineation model aiming to resolve several limitations in current generation watershed hydrology models and provides a uniform framework for both regional and global scale hydrologic simulation.
Beside, it provides an opportunity for coupled land-river-ocean modeling using a unified mesh.
Please advise any submission suggestions.
Thanks.

**Comment by changliao1025** [comment]
@kbarnhart I have recently updated the repository following earlier comments and instruction.

**Comment by kbarnhart** [comment]
@changliao1025 thanks for the ping. I will take a look and see if I have any comments. Given existing commitments, it will be difficult for me to look at this until late next week or early the following week.

**Comment by kbarnhart** [comment]
@changliao1025 I wanted to give you a quick update. It will be next week that I am able to look at this and get back to you.

**Comment by changliao1025** [comment]
Yes, any feedback will be helpful.

**Comment by kbarnhart** [comment]
Thank you for your patience.

**Comment by changliao1025** [comment]
@kbarnhart We recently moved the documentation to readthedocs because they provide better structure/features: https://hexwatershed.readthedocs.io/en/latest/

**Comment by kbarnhart** [comment]
@changliao1025. I have now completed an assessment of your repository and documentation. Thank you for your patience. Based on what I've looked at, it does not appear to me that the current repository and documentation would be accepted into review at JOSS. My concerns are very similar to what I indicated in my earlier rejection (openjournals/joss-reviews/issues/2751). Here I elaborate in more detail:

- There is no API-level documentation or lists of functions provided. I would expect that for each public facing function a detailed description of required inputs/outputs, and their formats would be provided. For example:
  - The format of the the .meta input file is not fully described, only a screenshot is given. 
  - While the documentation indicates that there is a strict file system tree structure, that structure's specification is not described on read-the-docs (appears to be better described on the subfolder's readme). 
  - no information regarding the nature of the hex mesh input shapefile. Is it a point, multi-point, polygon, multipolygon type shapefile? Are there requirements regarding feature ordering? Are there required entries in the attribute table? While it is perfectly acceptable to point users to another piece of software to make this input, it should be described so that a user does not need to use that software in order to use your software. 
  - no specific details provided related to the required buffer distance
  - no description of how the software handles interpolation between the hex mesh and the dem resolution. 
  - Beyond listing the outputs in the text, there is no detailed description of what the outputs are: what type of shapefile is created? what attributes are present?  
- No instructions are provided to run tests and thus verify that HexWatershed has been installed correctly and is producing correct results. 
- One example is given, but it is not extensively described. 

In addition to missing major elements (e.g., API-level description, tests), it is not clear that the implementation of the software and construction of associated materials meet the substantial scholarly effort criterion [outlined in the documentation](https://joss.readthedocs.io/en/latest/submitting.html?#substantial-scholarly-effort). The algorithms are described in a cited Environmental Modeling and Software publication (Liao et al., 2020), which is, of course, acceptable. However, under this circumstance JOSS expects that the implementation of the software and creation of related materials itself constitutes a substantial scholarly effort. We've worked to clarify this expectation in [the documentation](https://joss.readthedocs.io/en/latest/submitting.html#co-publication-of-science-methods-and-software). 

> Sometimes authors prepare a JOSS publication alongside a contribution describing a science application, details of algorithm development, and/or methods assessment. In this circumstance, JOSS considers submissions for which the implementation of the software itself reflects a substantial scientific effort. This may be represented by the design of the software, the implementation of the algorithms, creation of tutorials, or any other aspect of the software. 

Liao, C., Tesfa, T., Duan, Z., & Leung, L. R. (2020). Watershed delineation on a hexagonal mesh grid. Environmental Modelling & Software, 104702. https://doi.org/10.1016/j.envsoft.2020.104702

If you think that a revised package that includes all the required elements would meet the substantial scholarly effort requirement, I would encourage you to revise it. If you do this I would recommend that you carefully review the [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). 

If you have any questions or clarifications regarding my comments, please feel free to post them here or email me directly at krbarnhart@usgs.gov

Tagging the JOSS editors in chief, in case any of them have further comments @openjournals/joss-eics

**Comment by changliao1025** [comment]
@kbarnhart Thanks for all those constructive comments. I will revise the content to address them shortly.
