### ISSUE TITLE
master --> main

### ISSUE THREAD

**Issue by trashbirdecology** [openjournals/joss#827]
Suggest moving over to 'main' as the default branch

**Comment by xuanxu** [comment]
👍  Right now the move is difficult for already existing repos like this one, because it should include rebasing open PR, and branch permissions changes. 
But GitHub is working in a [one-click solution, announced for _later this year_](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) and we'll probably use it as soon as it's ready.

**Comment by trashbirdecology** [comment]
Oh nice, I hadn't seen that announcement! Thanks!!!

**Comment by marwahaha** [comment]
I think "renaming a branch" is now available.

**Comment by xuanxu** [comment]
Closing as this is done now
