### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by trashbirdecology** [openjournals/joss#850]
On behalf of the software's primary author, @natbprice, I submit this presubmission inquiry for R package [__tvdiff__](github.com/natbprice/tvdiff). Also tagging co-author @chrischizinski for funsies.

__JOSS submission materials for this package and paper [are here](https://github.com/natbprice/tvdiff/tree/main/inst/paper)__ 

To editor: I've tried a few times to resolve [whedon's image compilation error](https://whedon.theoj.org/preview?id=5152717d1d5b16d11d9390c8) but can't. Please let me know if you see something obvious here.

**Comment by arfon** [comment]
@trashbirdecology - it looks like this submission source code is in [this directory](https://github.com/natbprice/tvdiff/tree/main/R). Is that correct? If so, then this submission is very possibly out of scope due to our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by trashbirdecology** [comment]
@arfon, I realized I didn't respond to this. Apologies, you are correct. Closing issue.
