### ISSUE TITLE
Are the two "statement of need" items swapped?

### ISSUE THREAD

**Issue by jpsnijder** [openjournals/joss#882]
In the review checklist it seems to me that the _statement of need_ item under the documentation section is swapped with the statement of need item under the software paper section. It is because the _state of need_ item under the documentation section refers to "the paper", which I am assuming is the software paper that we are reviewing. Contrarily, the _state of need_ item under the software paper section seems more broad and could refer to a statement of need in the software's user documentation. Are they swapped? @oliviaguest

**Comment by danielskatz** [comment]
Yes, this is not as clear as it should be

**Comment by danielskatz** [comment]
Swapping is a good solution, so that the documentation item would be:

A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

while the software paper item would be

A statement of need: Does the paper  have a section titled ‘Statement of Need’ that clearly states what problems the software is designed to solve and who the target audience is?

**Comment by arfon** [comment]
Fixed in #883
