### ISSUE TITLE
Please regenerate https://joss.theoj.org/papers/10.21105/joss.00622 for updated Acknowledgements

### ISSUE THREAD

**Issue by ericfranz** [openjournals/joss#888]
Please regenerate the https://joss.theoj.org/papers/10.21105/joss.00622 document from the repo. I updated the Acknowledgements section to include the latest NSF award for the project https://github.com/OSC/ondemand/commit/93fb3da91a062221b49db4736cd2ffa67d2bd810

Also, for future reference, is this the appropriate way to make a request like this?

**Comment by danielskatz** [comment]
There's not a good answer, since once a paper is published, it shouldn't be changed, though a new version can be created by hand, which I think @arfon has to do. 

Given that this was published two years ago, I'm not even sure it makes sense to replace it with a new version - the version that was published then is now part of the scholarly record.

 cc @openjournals/joss-eics

**Comment by arfon** [comment]
> What do you propose would be the way to handle Open Source software that gets new funding sources that would like to be acknowledged?

I would suggest listing this perhaps on a project page (if you have one) or in the README on https://github.com/OSC/ondemand . We support updating papers a short period (days) after publishing when authors have forgotten to including information like this, but I agree with @danielskatz that we shouldn't here.

**Comment by danielskatz** [comment]
Think of this like any other published paper.  Would you go back to the publisher 3 years after it was published and ask the acknowledgments be updated because you got a new award related to the published work?

**Comment by ericfranz** [comment]
Thank makes sense, thank you!
