### ISSUE TITLE
Pre-submission inquiry

### ISSUE THREAD

**Issue by PharaohCola13** [openjournals/joss#939]
Dear Editors,

We are looking into writing up a short paper regarding the primary module and deployment of a utility that is being used in atmospheric science, the [Precipitable-Water Model Analysis Tool](https://github.com/physicsgoddess1972/Precipitable-Water-Model), and we wanted to see if this software was an appropriate topic for the Journal of Open Source Software. 

This tool has been used in research with the results being cited in a [paper](https://amt.copernicus.org/preprints/amt-2021-130) under review in Atmospheric Measurement Techniques. 

Thank you for your time,
Spencer

**Comment by kthyng** [comment]
Hi @PharaohCola13! A quick look indicates that this fits in scope in terms of being research software. The main question if you submitted would be if this is a [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), which you can approximately judge for yourself based on the guidelines in the journal docs linked. Generally, the software lines of code should be over 1000, and development should have occurred over more than 3 months; if it is borderline, the editorial board will have a closer look.  It is totally fine to also be publishing results in other journals if the focus in another paper is not on the software itself. In that case, we tend to require a somewhat higher bar for being a substantial scholarly effort in that case since the effort should be commensurately larger for the two publications (not "getting 2 papers" from 1 effort).

**Comment by PharaohCola13** [comment]
@kthyng Thank you for the response. 

I will review the guidelines again and make sure that everything is appropriately satisfied. I am certain that we have more than 1000 lines of code and the project has been actively worked on for on the order of two years. The current paper under review discusses the theory and results of our analysis with the software only being mentioned briefly.
