### ISSUE TITLE
JOSS documentation/whedon guidance fix needed to tell reviewers not to use github "convert to issue" from the checklist

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss#960]
I've had two reviews recently where a reviewer used the GitHub "convert to issue" function on a review checklist item. This leads to a new issue being created in https://github.com/openjournals/joss-reviews/issues, rather than in the repo, and the issue has no useful information other than the title of the checklist item.  See https://github.com/openjournals/joss-reviews/issues/3348 and https://github.com/openjournals/joss-reviews/issues/3466 as an example.

I guess this is a relatively new GitHub function that I would love to disable in our review issues (and I'm not alone, see https://github.com/github/feedback/discussions/4261 for example)

Given that we can't currently disable this, I think we need to change our documentation (and the instructions that when provides) to tell reviewers not to use this, and that they need to manually open an issue in the repository of the software being reviewed instead.

**Comment by arfon** [comment]
I don't think we need this any longer. We have a short term fix which is to auto-close non review related issues (see example: https://github.com/openjournals/joss-reviews/issues/4216), and the longer-term fix which is that this is no longer a problem for reviews created since our migration to EditorialBot.
